linux:
  hosts:
    storagectrl:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ control_plane_ip }}"
    storagewrkr0:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[0] }}"
    storagewrkr1:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[1] }}"
    storagewrkr2:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[2] }}"
    #storagewrkr3:
    #  ansible_user: "{{ ssh_user }}"
    #  ansible_host: "{{ worker_ips[3] }}"
    #storagewrkr4:
    #  ansible_user: "{{ ssh_user }}"
    #  ansible_host: "{{ worker_ips[4] }}"

vms:
  hosts:
    storagectrl:
    storagewrkr0:
    storagewrkr1:
    storagewrkr2:
    #storagewrkr3:
    #storagewrkr4:

controllers:
  hosts:
    storagectrl:
  
workers:
  hosts:
    storagewrkr0:
    storagewrkr1:
    storagewrkr2:
    #storagewrkr3:
    #storagewrkr4: