---
- name: Create newt namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: newt
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Apply Manifest
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', repo_root + '/apps/pangolin-newt/manifest.yml') | from_yaml_all | list }}"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"